{{- if eq .Values.database.mode "internal" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "patchmon.fullname" . }}-postgres
spec:
  selector:
    {{- include "patchmon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
{{- end }}
