apiVersion: v1
kind: Service
metadata:
  name: {{ include "patchmon.fullname" . }}-backend
  labels:
    {{- include "patchmon.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    {{- include "patchmon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.service.backend.port }}
      targetPort: 3001
