apiVersion: v1
kind: Service
metadata:
  name: {{ include "patchmon.fullname" . }}-frontend
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    {{- include "patchmon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.service.frontend.port }}
      targetPort: 3000
