apiVersion: v2
name: patchmon
description: PatchMon (backend + frontend) with optional Gateway API, Postgres, and Valkey
type: application
version: 0.1.2
appVersion: "1.3.7"

dependencies:
  - name: valkey
    version: "^0.9.2"
    repository: "https://valkey.io/valkey-helm/"
    condition: valkey.enabled
