apiVersion: v2
name: patchmon
description: PatchMon (backend + frontend) with optional Gateway API, Postgres, and Valkey
type: application
version: 0.2.10
appVersion: "1.4.0"

maintainers:
  - name: HellstromIT
    url: https://github.com/HellstromIT

dependencies:
  - name: valkey
    version: "^0.9.2"
    repository: "https://valkey.io/valkey-helm/"
    condition: valkey.enabled
